version: '2'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: zzz
      MYSQL_USER: root
      MYSQL_PASSWORD: zzz
      MYSQL_DATABASE: zzz
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --appendonly yes
        ports:
      # We'll bind our host's port 6379 to redis's port 6379, so we can use
      # Redis Desktop Manager (or other tools) with it:
      - 6379:6379
    # volumes:
    #   - 'redis:/data'
  web:
    build: .
    command: bundle exec rails s
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/app'
    env_file:
      - '.env'
